[package]
name = "chess_ai"
version = "0.1.0"
authors = ["nealian <nealian@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
regex = "1.5.4"
lazy_static = "1.4.0"